<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="11" passed="10" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-15T18:38:50 IST" name="RegressionTest" finished-at="2022-03-15T18:40:05 IST" duration-ms="75014">
    <groups>
    </groups>
    <test started-at="2022-03-15T18:38:50 IST" name="LoginTest" finished-at="2022-03-15T18:40:05 IST" duration-ms="75014">
      <class name="test.LoginTest">
        <test-method signature="open_the_LoginPage_Url()[pri:1, instance:test.LoginTest@6236eb5f]" started-at="2022-03-15T18:38:50 IST" name="open_the_LoginPage_Url" finished-at="2022-03-15T18:39:30 IST" duration-ms="40420" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_the_LoginPage_Url -->
        <test-method signature="enter_valid_username_and_invalid_password()[pri:2, instance:test.LoginTest@6236eb5f]" started-at="2022-03-15T18:39:30 IST" name="enter_valid_username_and_invalid_password" finished-at="2022-03-15T18:39:35 IST" duration-ms="4767" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_valid_username_and_invalid_password -->
        <test-method signature="enter_invalid_username_and_valid_password()[pri:3, instance:test.LoginTest@6236eb5f]" started-at="2022-03-15T18:39:35 IST" name="enter_invalid_username_and_valid_password" finished-at="2022-03-15T18:39:39 IST" duration-ms="4217" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_invalid_username_and_valid_password -->
        <test-method signature="enter_valid_username_and_empty_password()[pri:4, instance:test.LoginTest@6236eb5f]" started-at="2022-03-15T18:39:39 IST" name="enter_valid_username_and_empty_password" finished-at="2022-03-15T18:39:43 IST" duration-ms="4194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_valid_username_and_empty_password -->
        <test-method signature="enter_invalid_username_and_empty_password()[pri:5, instance:test.LoginTest@6236eb5f]" started-at="2022-03-15T18:39:43 IST" name="enter_invalid_username_and_empty_password" finished-at="2022-03-15T18:39:48 IST" duration-ms="4167" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_invalid_username_and_empty_password -->
        <test-method signature="enter_empty_username_and_valid_password()[pri:6, instance:test.LoginTest@6236eb5f]" started-at="2022-03-15T18:39:48 IST" name="enter_empty_username_and_valid_password" finished-at="2022-03-15T18:39:52 IST" duration-ms="4167" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_empty_username_and_valid_password -->
        <test-method signature="enter_empty_username_and_invalid_password()[pri:7, instance:test.LoginTest@6236eb5f]" started-at="2022-03-15T18:39:52 IST" name="enter_empty_username_and_invalid_password" finished-at="2022-03-15T18:39:56 IST" duration-ms="4182" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_empty_username_and_invalid_password -->
        <test-method signature="enter_empty_username_and_empty_password()[pri:8, instance:test.LoginTest@6236eb5f]" started-at="2022-03-15T18:39:56 IST" name="enter_empty_username_and_empty_password" finished-at="2022-03-15T18:40:00 IST" duration-ms="4171" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_empty_username_and_empty_password -->
        <test-method signature="enter_invalid_username_and_invalid_password()[pri:9, instance:test.LoginTest@6236eb5f]" started-at="2022-03-15T18:40:00 IST" name="enter_invalid_username_and_invalid_password" finished-at="2022-03-15T18:40:04 IST" duration-ms="4209" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_invalid_username_and_invalid_password -->
        <test-method signature="enter_valid_username_and_valid_password()[pri:10, instance:test.LoginTest@6236eb5f]" started-at="2022-03-15T18:40:04 IST" name="enter_valid_username_and_valid_password" finished-at="2022-03-15T18:40:05 IST" duration-ms="195" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getRow(int)" because the return value of "org.apache.poi.ss.usermodel.Workbook.getSheet(String)" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getRow(int)" because the return value of "org.apache.poi.ss.usermodel.Workbook.getSheet(String)" is null
at test.LoginTest.enter_valid_username_and_valid_password(LoginTest.java:143)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_valid_username_and_valid_password -->
        <test-method signature="enter_valid_username_and_invalid_password1()[pri:11, instance:test.LoginTest@6236eb5f]" started-at="2022-03-15T18:40:05 IST" name="enter_valid_username_and_invalid_password1" finished-at="2022-03-15T18:40:05 IST" duration-ms="266" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_valid_username_and_invalid_password1 -->
      </class> <!-- test.LoginTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- RegressionTest -->
</testng-results>
